from types import MappingProxyType


GOOD_IMAGE = -1


LOW_IMAGE_QUALITY_SMALL_ERROR = 1
LOW_IMAGE_QUALITY_BLURRY_ERROR = 2
LOW_IMAGE_QUALITY_DARK_ERROR = 3
LOW_IMAGE_QUALITY_BRIGHT_ERROR = 4
LOW_IMAGE_QUALITY_BAD_ILLUMINATION_ERROR = 5
LOW_IMAGE_QUALITY_NOT_CONTRAST_ERROR = 6
LOW_CAR_QUALITY_NO_CAR_ERROR = 7
LOW_CAR_QUALITY_SMALL_CAR_ERROR = 8
LOW_CAR_QUALITY_NOT_CENTERED_CAR_ERROR = 9
LOW_CAR_QUALITY_CAR_AMBIGUITY_ERROR = 10



default_validation_config = {
    'MIN_WIDTH': 1024.0,
    'MIN_HEIGHT': 768.0,
    'MIN_WIDTH_DEVIATION': 0.8,
    'MIN_HEIGHT_DEVIATION': 0.8,
    'BLURRINESS_THRESHOLD': 100.0,
    'CAR_SCORE_THRESHOLD': 0.91,
    'CAR_MIN_AREA_THRESHOLD': 0.6,
    'TWO_BIGGEST_CARS_RATIO_THRESHOLD': 2.5,
    'CAR_CENTER_DEVIATION_THRESHOLD': 0.2,
    'NORMALITY_TEST_CHI_SQUARED_PROB_THRESHOLD': 3.27207e-30,
    'DARK_THRESHOLD': 0.5,
    'BRIGHT_THRESHOLD': 0.4
    
}
DEFAULT_VALIDATION_CONFIG = MappingProxyType(default_validation_config)